//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/gheor/Desktop/Facultate/Anul II/LFC/LFC2/LFC2/OurCompiler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class OurCompilerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LINECOMMENT=1, BIGCOMMENT=2, INT=3, FLOAT=4, DOUBLE=5, STRING=6, CONST=7, 
		VOID=8, IF=9, ELSE=10, FOR=11, WHILE=12, RETURN=13, PLUS=14, MINUS=15, 
		TIMES=16, DIVIDED=17, MODULO=18, AND=19, OR=20, NOT=21, ASGN=22, ASGN_PLUS=23, 
		ASGN_MINUS=24, ASGN_TIMES=25, ASGN_DIVIDED=26, ASGN_MODULO=27, LESS=28, 
		GREAT=29, EQ=30, NEQ=31, LESSOREQ=32, GREATOREQ=33, INCREMENT=34, DECREMENT=35, 
		LPAR=36, RPAR=37, LGROUP=38, RGROUP=39, EOL=40, COMMA=41, WS=42, VARIABLE_NAME=43, 
		INT_NUMBER=44, DOUBLE_NUMBER=45, FLOAT_NUMBER=46, STRING_LITERAL=47;
	public const int
		RULE_pure_data = 0, RULE_data_type = 1, RULE_any_math_operator = 2, RULE_math_expr = 3, 
		RULE_comp_val = 4, RULE_comparer = 5, RULE_logic_link = 6, RULE_logic_expr = 7, 
		RULE_crement_expr = 8, RULE_program = 9, RULE_function = 10, RULE_expression_generator = 11, 
		RULE_expression = 12, RULE_var_declar_expr = 13, RULE_var_assign_expr = 14, 
		RULE_var_decl_assg_expr = 15, RULE_if_expr = 16, RULE_for_expr = 17, RULE_while_expr = 18, 
		RULE_return_expr = 19, RULE_function_call_expr = 20;
	public static readonly string[] ruleNames = {
		"pure_data", "data_type", "any_math_operator", "math_expr", "comp_val", 
		"comparer", "logic_link", "logic_expr", "crement_expr", "program", "function", 
		"expression_generator", "expression", "var_declar_expr", "var_assign_expr", 
		"var_decl_assg_expr", "if_expr", "for_expr", "while_expr", "return_expr", 
		"function_call_expr"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "'int'", "'float'", "'double'", "'string'", "'const'", 
		"'void'", "'if'", "'else'", "'for'", "'while'", "'return'", "'+'", "'-'", 
		"'*'", "'/'", "'%'", "'&&'", "'||'", "'!'", "'='", "'+='", "'-='", "'*='", 
		"'/='", "'%='", "'<'", "'>'", "'=='", "'!='", "'<='", "'>='", "'++'", 
		"'--'", "'('", "')'", "'{'", "'}'", "';'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LINECOMMENT", "BIGCOMMENT", "INT", "FLOAT", "DOUBLE", "STRING", 
		"CONST", "VOID", "IF", "ELSE", "FOR", "WHILE", "RETURN", "PLUS", "MINUS", 
		"TIMES", "DIVIDED", "MODULO", "AND", "OR", "NOT", "ASGN", "ASGN_PLUS", 
		"ASGN_MINUS", "ASGN_TIMES", "ASGN_DIVIDED", "ASGN_MODULO", "LESS", "GREAT", 
		"EQ", "NEQ", "LESSOREQ", "GREATOREQ", "INCREMENT", "DECREMENT", "LPAR", 
		"RPAR", "LGROUP", "RGROUP", "EOL", "COMMA", "WS", "VARIABLE_NAME", "INT_NUMBER", 
		"DOUBLE_NUMBER", "FLOAT_NUMBER", "STRING_LITERAL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "OurCompiler.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static OurCompilerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public OurCompilerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public OurCompilerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Pure_dataContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_NUMBER() { return GetToken(OurCompilerParser.INT_NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_NUMBER() { return GetToken(OurCompilerParser.FLOAT_NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_NUMBER() { return GetToken(OurCompilerParser.DOUBLE_NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(OurCompilerParser.STRING_LITERAL, 0); }
		public Pure_dataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pure_data; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPure_data(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pure_dataContext pure_data() {
		Pure_dataContext _localctx = new Pure_dataContext(Context, State);
		EnterRule(_localctx, 0, RULE_pure_data);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 263882790666240L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Data_typeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(OurCompilerParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(OurCompilerParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT() { return GetToken(OurCompilerParser.FLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(OurCompilerParser.DOUBLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONST() { return GetToken(OurCompilerParser.CONST, 0); }
		public Data_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_data_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitData_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Data_typeContext data_type() {
		Data_typeContext _localctx = new Data_typeContext(Context, State);
		EnterRule(_localctx, 2, RULE_data_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==CONST) {
				{
				State = 44;
				Match(CONST);
				}
			}

			State = 47;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 120L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Any_math_operatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(OurCompilerParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(OurCompilerParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TIMES() { return GetToken(OurCompilerParser.TIMES, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIVIDED() { return GetToken(OurCompilerParser.DIVIDED, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MODULO() { return GetToken(OurCompilerParser.MODULO, 0); }
		public Any_math_operatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_any_math_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAny_math_operator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Any_math_operatorContext any_math_operator() {
		Any_math_operatorContext _localctx = new Any_math_operatorContext(Context, State);
		EnterRule(_localctx, 4, RULE_any_math_operator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 49;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 507904L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Math_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Any_math_operatorContext[] any_math_operator() {
			return GetRuleContexts<Any_math_operatorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Any_math_operatorContext any_math_operator(int i) {
			return GetRuleContext<Any_math_operatorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VARIABLE_NAME() { return GetTokens(OurCompilerParser.VARIABLE_NAME); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME(int i) {
			return GetToken(OurCompilerParser.VARIABLE_NAME, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext[] pure_data() {
			return GetRuleContexts<Pure_dataContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext pure_data(int i) {
			return GetRuleContext<Pure_dataContext>(i);
		}
		public Math_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_math_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMath_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Math_exprContext math_expr() {
		Math_exprContext _localctx = new Math_exprContext(Context, State);
		EnterRule(_localctx, 6, RULE_math_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE_NAME:
				{
				State = 51;
				Match(VARIABLE_NAME);
				}
				break;
			case INT_NUMBER:
			case DOUBLE_NUMBER:
			case FLOAT_NUMBER:
			case STRING_LITERAL:
				{
				State = 52;
				pure_data();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 55;
			any_math_operator();
			State = 58;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE_NAME:
				{
				State = 56;
				Match(VARIABLE_NAME);
				}
				break;
			case INT_NUMBER:
			case DOUBLE_NUMBER:
			case FLOAT_NUMBER:
			case STRING_LITERAL:
				{
				State = 57;
				pure_data();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 67;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 507904L) != 0)) {
				{
				{
				State = 60;
				any_math_operator();
				State = 63;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case VARIABLE_NAME:
					{
					State = 61;
					Match(VARIABLE_NAME);
					}
					break;
				case INT_NUMBER:
				case DOUBLE_NUMBER:
				case FLOAT_NUMBER:
				case STRING_LITERAL:
					{
					State = 62;
					pure_data();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				}
				State = 69;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Comp_valContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(OurCompilerParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext pure_data() {
			return GetRuleContext<Pure_dataContext>(0);
		}
		public Comp_valContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comp_val; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComp_val(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Comp_valContext comp_val() {
		Comp_valContext _localctx = new Comp_valContext(Context, State);
		EnterRule(_localctx, 8, RULE_comp_val);
		try {
			State = 72;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE_NAME:
				EnterOuterAlt(_localctx, 1);
				{
				State = 70;
				Match(VARIABLE_NAME);
				}
				break;
			case INT_NUMBER:
			case DOUBLE_NUMBER:
			case FLOAT_NUMBER:
			case STRING_LITERAL:
				EnterOuterAlt(_localctx, 2);
				{
				State = 71;
				pure_data();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS() { return GetToken(OurCompilerParser.LESS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREAT() { return GetToken(OurCompilerParser.GREAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(OurCompilerParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEQ() { return GetToken(OurCompilerParser.NEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESSOREQ() { return GetToken(OurCompilerParser.LESSOREQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATOREQ() { return GetToken(OurCompilerParser.GREATOREQ, 0); }
		public ComparerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparer(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparerContext comparer() {
		ComparerContext _localctx = new ComparerContext(Context, State);
		EnterRule(_localctx, 10, RULE_comparer);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 16911433728L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Logic_linkContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(OurCompilerParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(OurCompilerParser.OR, 0); }
		public Logic_linkContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logic_link; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogic_link(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Logic_linkContext logic_link() {
		Logic_linkContext _localctx = new Logic_linkContext(Context, State);
		EnterRule(_localctx, 12, RULE_logic_link);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76;
			_la = TokenStream.LA(1);
			if ( !(_la==AND || _la==OR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Logic_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Comp_valContext[] comp_val() {
			return GetRuleContexts<Comp_valContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Comp_valContext comp_val(int i) {
			return GetRuleContext<Comp_valContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparerContext comparer() {
			return GetRuleContext<ComparerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Logic_linkContext logic_link() {
			return GetRuleContext<Logic_linkContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(OurCompilerParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAR() { return GetToken(OurCompilerParser.LPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAR() { return GetToken(OurCompilerParser.RPAR, 0); }
		public Logic_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logic_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogic_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Logic_exprContext logic_expr() {
		Logic_exprContext _localctx = new Logic_exprContext(Context, State);
		EnterRule(_localctx, 14, RULE_logic_expr);
		int _la;
		try {
			State = 98;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE_NAME:
			case INT_NUMBER:
			case DOUBLE_NUMBER:
			case FLOAT_NUMBER:
			case STRING_LITERAL:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 78;
				comp_val();
				State = 79;
				comparer();
				State = 80;
				comp_val();
				State = 84;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AND || _la==OR) {
					{
					State = 81;
					logic_link();
					State = 82;
					logic_expr();
					}
				}

				}
				}
				break;
			case NOT:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 86;
				Match(NOT);
				State = 87;
				Match(LPAR);
				State = 88;
				comp_val();
				State = 89;
				comparer();
				State = 90;
				comp_val();
				State = 94;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AND || _la==OR) {
					{
					State = 91;
					logic_link();
					State = 92;
					logic_expr();
					}
				}

				State = 96;
				Match(RPAR);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Crement_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(OurCompilerParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INCREMENT() { return GetToken(OurCompilerParser.INCREMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECREMENT() { return GetToken(OurCompilerParser.DECREMENT, 0); }
		public Crement_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_crement_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCrement_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Crement_exprContext crement_expr() {
		Crement_exprContext _localctx = new Crement_exprContext(Context, State);
		EnterRule(_localctx, 16, RULE_crement_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			Match(VARIABLE_NAME);
			State = 101;
			_la = TokenStream.LA(1);
			if ( !(_la==INCREMENT || _la==DECREMENT) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(OurCompilerParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext[] function() {
			return GetRuleContexts<FunctionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function(int i) {
			return GetRuleContext<FunctionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_declar_exprContext[] var_declar_expr() {
			return GetRuleContexts<Var_declar_exprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_declar_exprContext var_declar_expr(int i) {
			return GetRuleContext<Var_declar_exprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] EOL() { return GetTokens(OurCompilerParser.EOL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EOL(int i) {
			return GetToken(OurCompilerParser.EOL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_decl_assg_exprContext[] var_decl_assg_expr() {
			return GetRuleContexts<Var_decl_assg_exprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_decl_assg_exprContext var_decl_assg_expr(int i) {
			return GetRuleContext<Var_decl_assg_exprContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 18, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 110;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
				case 1:
					{
					State = 103;
					function();
					}
					break;
				case 2:
					{
					{
					State = 104;
					var_declar_expr();
					State = 105;
					Match(EOL);
					}
					}
					break;
				case 3:
					{
					{
					State = 107;
					var_decl_assg_expr();
					State = 108;
					Match(EOL);
					}
					}
					break;
				}
				}
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 504L) != 0) );
			State = 114;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VARIABLE_NAME() { return GetTokens(OurCompilerParser.VARIABLE_NAME); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME(int i) {
			return GetToken(OurCompilerParser.VARIABLE_NAME, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAR() { return GetToken(OurCompilerParser.LPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAR() { return GetToken(OurCompilerParser.RPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LGROUP() { return GetToken(OurCompilerParser.LGROUP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expression_generatorContext expression_generator() {
			return GetRuleContext<Expression_generatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RGROUP() { return GetToken(OurCompilerParser.RGROUP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Data_typeContext[] data_type() {
			return GetRuleContexts<Data_typeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Data_typeContext data_type(int i) {
			return GetRuleContext<Data_typeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VOID() { return GetToken(OurCompilerParser.VOID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(OurCompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(OurCompilerParser.COMMA, i);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 20, RULE_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
			case FLOAT:
			case DOUBLE:
			case STRING:
			case CONST:
				{
				State = 116;
				data_type();
				}
				break;
			case VOID:
				{
				State = 117;
				Match(VOID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 120;
			Match(VARIABLE_NAME);
			State = 121;
			Match(LPAR);
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 248L) != 0)) {
				{
				State = 122;
				data_type();
				State = 123;
				Match(VARIABLE_NAME);
				State = 130;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 124;
					Match(COMMA);
					State = 125;
					data_type();
					State = 126;
					Match(VARIABLE_NAME);
					}
					}
					State = 132;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 135;
			Match(RPAR);
			State = 136;
			Match(LGROUP);
			State = 137;
			expression_generator();
			State = 138;
			Match(RGROUP);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_generatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Expression_generatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_generator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_generator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_generatorContext expression_generator() {
		Expression_generatorContext _localctx = new Expression_generatorContext(Context, State);
		EnterRule(_localctx, 22, RULE_expression_generator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 143;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 8796093037304L) != 0)) {
				{
				{
				State = 140;
				expression();
				}
				}
				State = 145;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EOL() { return GetToken(OurCompilerParser.EOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_declar_exprContext var_declar_expr() {
			return GetRuleContext<Var_declar_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_assign_exprContext var_assign_expr() {
			return GetRuleContext<Var_assign_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_decl_assg_exprContext var_decl_assg_expr() {
			return GetRuleContext<Var_decl_assg_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Crement_exprContext crement_expr() {
			return GetRuleContext<Crement_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Return_exprContext return_expr() {
			return GetRuleContext<Return_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Function_call_exprContext function_call_expr() {
			return GetRuleContext<Function_call_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public If_exprContext if_expr() {
			return GetRuleContext<If_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_exprContext for_expr() {
			return GetRuleContext<For_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public While_exprContext while_expr() {
			return GetRuleContext<While_exprContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 24, RULE_expression);
		try {
			State = 161;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
			case FLOAT:
			case DOUBLE:
			case STRING:
			case CONST:
			case RETURN:
			case VARIABLE_NAME:
				EnterOuterAlt(_localctx, 1);
				{
				State = 152;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
				case 1:
					{
					State = 146;
					var_declar_expr();
					}
					break;
				case 2:
					{
					State = 147;
					var_assign_expr();
					}
					break;
				case 3:
					{
					State = 148;
					var_decl_assg_expr();
					}
					break;
				case 4:
					{
					State = 149;
					crement_expr();
					}
					break;
				case 5:
					{
					State = 150;
					return_expr();
					}
					break;
				case 6:
					{
					State = 151;
					function_call_expr();
					}
					break;
				}
				State = 154;
				Match(EOL);
				}
				break;
			case IF:
			case FOR:
			case WHILE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 159;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case IF:
					{
					State = 156;
					if_expr();
					}
					break;
				case FOR:
					{
					State = 157;
					for_expr();
					}
					break;
				case WHILE:
					{
					State = 158;
					while_expr();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_declar_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Data_typeContext data_type() {
			return GetRuleContext<Data_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(OurCompilerParser.VARIABLE_NAME, 0); }
		public Var_declar_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_declar_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_declar_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_declar_exprContext var_declar_expr() {
		Var_declar_exprContext _localctx = new Var_declar_exprContext(Context, State);
		EnterRule(_localctx, 26, RULE_var_declar_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			data_type();
			State = 164;
			Match(VARIABLE_NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_assign_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VARIABLE_NAME() { return GetTokens(OurCompilerParser.VARIABLE_NAME); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME(int i) {
			return GetToken(OurCompilerParser.VARIABLE_NAME, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASGN() { return GetToken(OurCompilerParser.ASGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext pure_data() {
			return GetRuleContext<Pure_dataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Math_exprContext math_expr() {
			return GetRuleContext<Math_exprContext>(0);
		}
		public Var_assign_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_assign_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_assign_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_assign_exprContext var_assign_expr() {
		Var_assign_exprContext _localctx = new Var_assign_exprContext(Context, State);
		EnterRule(_localctx, 28, RULE_var_assign_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166;
			Match(VARIABLE_NAME);
			State = 167;
			Match(ASGN);
			State = 171;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				{
				State = 168;
				pure_data();
				}
				break;
			case 2:
				{
				State = 169;
				Match(VARIABLE_NAME);
				}
				break;
			case 3:
				{
				State = 170;
				math_expr();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_decl_assg_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Data_typeContext data_type() {
			return GetRuleContext<Data_typeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VARIABLE_NAME() { return GetTokens(OurCompilerParser.VARIABLE_NAME); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME(int i) {
			return GetToken(OurCompilerParser.VARIABLE_NAME, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASGN() { return GetToken(OurCompilerParser.ASGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext pure_data() {
			return GetRuleContext<Pure_dataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Math_exprContext math_expr() {
			return GetRuleContext<Math_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Function_call_exprContext function_call_expr() {
			return GetRuleContext<Function_call_exprContext>(0);
		}
		public Var_decl_assg_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_decl_assg_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_decl_assg_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_decl_assg_exprContext var_decl_assg_expr() {
		Var_decl_assg_exprContext _localctx = new Var_decl_assg_exprContext(Context, State);
		EnterRule(_localctx, 30, RULE_var_decl_assg_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			data_type();
			State = 174;
			Match(VARIABLE_NAME);
			State = 175;
			Match(ASGN);
			State = 180;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				{
				State = 176;
				pure_data();
				}
				break;
			case 2:
				{
				State = 177;
				Match(VARIABLE_NAME);
				}
				break;
			case 3:
				{
				State = 178;
				math_expr();
				}
				break;
			case 4:
				{
				State = 179;
				function_call_expr();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(OurCompilerParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAR() { return GetToken(OurCompilerParser.LPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAR() { return GetToken(OurCompilerParser.RPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LGROUP() { return GetTokens(OurCompilerParser.LGROUP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LGROUP(int i) {
			return GetToken(OurCompilerParser.LGROUP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_generatorContext[] expression_generator() {
			return GetRuleContexts<Expression_generatorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expression_generatorContext expression_generator(int i) {
			return GetRuleContext<Expression_generatorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RGROUP() { return GetTokens(OurCompilerParser.RGROUP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RGROUP(int i) {
			return GetToken(OurCompilerParser.RGROUP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(OurCompilerParser.ELSE, 0); }
		public If_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public If_exprContext if_expr() {
		If_exprContext _localctx = new If_exprContext(Context, State);
		EnterRule(_localctx, 32, RULE_if_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			Match(IF);
			State = 183;
			Match(LPAR);
			State = 184;
			logic_expr();
			State = 185;
			Match(RPAR);
			State = 191;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
			case FLOAT:
			case DOUBLE:
			case STRING:
			case CONST:
			case IF:
			case FOR:
			case WHILE:
			case RETURN:
			case VARIABLE_NAME:
				{
				State = 186;
				expression();
				}
				break;
			case LGROUP:
				{
				State = 187;
				Match(LGROUP);
				State = 188;
				expression_generator();
				State = 189;
				Match(RGROUP);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 201;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				{
				State = 193;
				Match(ELSE);
				State = 199;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case INT:
				case FLOAT:
				case DOUBLE:
				case STRING:
				case CONST:
				case IF:
				case FOR:
				case WHILE:
				case RETURN:
				case VARIABLE_NAME:
					{
					State = 194;
					expression();
					}
					break;
				case LGROUP:
					{
					State = 195;
					Match(LGROUP);
					State = 196;
					expression_generator();
					State = 197;
					Match(RGROUP);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(OurCompilerParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAR() { return GetToken(OurCompilerParser.LPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] EOL() { return GetTokens(OurCompilerParser.EOL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EOL(int i) {
			return GetToken(OurCompilerParser.EOL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAR() { return GetToken(OurCompilerParser.RPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_assign_exprContext[] var_assign_expr() {
			return GetRuleContexts<Var_assign_exprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_assign_exprContext var_assign_expr(int i) {
			return GetRuleContext<Var_assign_exprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_decl_assg_exprContext var_decl_assg_expr() {
			return GetRuleContext<Var_decl_assg_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Crement_exprContext crement_expr() {
			return GetRuleContext<Crement_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LGROUP() { return GetToken(OurCompilerParser.LGROUP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expression_generatorContext expression_generator() {
			return GetRuleContext<Expression_generatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RGROUP() { return GetToken(OurCompilerParser.RGROUP, 0); }
		public For_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_exprContext for_expr() {
		For_exprContext _localctx = new For_exprContext(Context, State);
		EnterRule(_localctx, 34, RULE_for_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203;
			Match(FOR);
			State = 204;
			Match(LPAR);
			State = 207;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE_NAME:
				{
				State = 205;
				var_assign_expr();
				}
				break;
			case INT:
			case FLOAT:
			case DOUBLE:
			case STRING:
			case CONST:
				{
				State = 206;
				var_decl_assg_expr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 209;
			Match(EOL);
			State = 210;
			logic_expr();
			State = 211;
			Match(EOL);
			State = 214;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				{
				State = 212;
				crement_expr();
				}
				break;
			case 2:
				{
				State = 213;
				var_assign_expr();
				}
				break;
			}
			State = 216;
			Match(RPAR);
			State = 222;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
			case FLOAT:
			case DOUBLE:
			case STRING:
			case CONST:
			case IF:
			case FOR:
			case WHILE:
			case RETURN:
			case VARIABLE_NAME:
				{
				State = 217;
				expression();
				}
				break;
			case LGROUP:
				{
				State = 218;
				Match(LGROUP);
				State = 219;
				expression_generator();
				State = 220;
				Match(RGROUP);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(OurCompilerParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAR() { return GetToken(OurCompilerParser.LPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAR() { return GetToken(OurCompilerParser.RPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LGROUP() { return GetToken(OurCompilerParser.LGROUP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expression_generatorContext expression_generator() {
			return GetRuleContext<Expression_generatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RGROUP() { return GetToken(OurCompilerParser.RGROUP, 0); }
		public While_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public While_exprContext while_expr() {
		While_exprContext _localctx = new While_exprContext(Context, State);
		EnterRule(_localctx, 36, RULE_while_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 224;
			Match(WHILE);
			State = 225;
			Match(LPAR);
			State = 226;
			logic_expr();
			State = 227;
			Match(RPAR);
			State = 233;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
			case FLOAT:
			case DOUBLE:
			case STRING:
			case CONST:
			case IF:
			case FOR:
			case WHILE:
			case RETURN:
			case VARIABLE_NAME:
				{
				State = 228;
				expression();
				}
				break;
			case LGROUP:
				{
				State = 229;
				Match(LGROUP);
				State = 230;
				expression_generator();
				State = 231;
				Match(RGROUP);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Return_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(OurCompilerParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext pure_data() {
			return GetRuleContext<Pure_dataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME() { return GetToken(OurCompilerParser.VARIABLE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Math_exprContext math_expr() {
			return GetRuleContext<Math_exprContext>(0);
		}
		public Return_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturn_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Return_exprContext return_expr() {
		Return_exprContext _localctx = new Return_exprContext(Context, State);
		EnterRule(_localctx, 38, RULE_return_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 235;
			Match(RETURN);
			State = 239;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
			case 1:
				{
				State = 236;
				pure_data();
				}
				break;
			case 2:
				{
				State = 237;
				Match(VARIABLE_NAME);
				}
				break;
			case 3:
				{
				State = 238;
				math_expr();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_call_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VARIABLE_NAME() { return GetTokens(OurCompilerParser.VARIABLE_NAME); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE_NAME(int i) {
			return GetToken(OurCompilerParser.VARIABLE_NAME, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAR() { return GetToken(OurCompilerParser.LPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAR() { return GetToken(OurCompilerParser.RPAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext[] pure_data() {
			return GetRuleContexts<Pure_dataContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pure_dataContext pure_data(int i) {
			return GetRuleContext<Pure_dataContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(OurCompilerParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(OurCompilerParser.COMMA, i);
		}
		public Function_call_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_call_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOurCompilerVisitor<TResult> typedVisitor = visitor as IOurCompilerVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction_call_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Function_call_exprContext function_call_expr() {
		Function_call_exprContext _localctx = new Function_call_exprContext(Context, State);
		EnterRule(_localctx, 40, RULE_function_call_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 241;
			Match(VARIABLE_NAME);
			State = 242;
			Match(LPAR);
			State = 257;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 272678883688448L) != 0)) {
				{
				State = 245;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case VARIABLE_NAME:
					{
					State = 243;
					Match(VARIABLE_NAME);
					}
					break;
				case INT_NUMBER:
				case DOUBLE_NUMBER:
				case FLOAT_NUMBER:
				case STRING_LITERAL:
					{
					State = 244;
					pure_data();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 254;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 247;
					Match(COMMA);
					State = 250;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case VARIABLE_NAME:
						{
						State = 248;
						Match(VARIABLE_NAME);
						}
						break;
					case INT_NUMBER:
					case DOUBLE_NUMBER:
					case FLOAT_NUMBER:
					case STRING_LITERAL:
						{
						State = 249;
						pure_data();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					}
					State = 256;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 259;
			Match(RPAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,47,262,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,1,0,1,0,1,
		1,3,1,46,8,1,1,1,1,1,1,2,1,2,1,3,1,3,3,3,54,8,3,1,3,1,3,1,3,3,3,59,8,3,
		1,3,1,3,1,3,3,3,64,8,3,5,3,66,8,3,10,3,12,3,69,9,3,1,4,1,4,3,4,73,8,4,
		1,5,1,5,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,7,3,7,85,8,7,1,7,1,7,1,7,1,7,1,7,
		1,7,1,7,1,7,3,7,95,8,7,1,7,1,7,3,7,99,8,7,1,8,1,8,1,8,1,9,1,9,1,9,1,9,
		1,9,1,9,1,9,4,9,111,8,9,11,9,12,9,112,1,9,1,9,1,10,1,10,3,10,119,8,10,
		1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,5,10,129,8,10,10,10,12,10,132,
		9,10,3,10,134,8,10,1,10,1,10,1,10,1,10,1,10,1,11,5,11,142,8,11,10,11,12,
		11,145,9,11,1,12,1,12,1,12,1,12,1,12,1,12,3,12,153,8,12,1,12,1,12,1,12,
		1,12,1,12,3,12,160,8,12,3,12,162,8,12,1,13,1,13,1,13,1,14,1,14,1,14,1,
		14,1,14,3,14,172,8,14,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,181,8,15,
		1,16,1,16,1,16,1,16,1,16,1,16,1,16,1,16,1,16,3,16,192,8,16,1,16,1,16,1,
		16,1,16,1,16,1,16,3,16,200,8,16,3,16,202,8,16,1,17,1,17,1,17,1,17,3,17,
		208,8,17,1,17,1,17,1,17,1,17,1,17,3,17,215,8,17,1,17,1,17,1,17,1,17,1,
		17,1,17,3,17,223,8,17,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,3,18,
		234,8,18,1,19,1,19,1,19,1,19,3,19,240,8,19,1,20,1,20,1,20,1,20,3,20,246,
		8,20,1,20,1,20,1,20,3,20,251,8,20,5,20,253,8,20,10,20,12,20,256,9,20,3,
		20,258,8,20,1,20,1,20,1,20,0,0,21,0,2,4,6,8,10,12,14,16,18,20,22,24,26,
		28,30,32,34,36,38,40,0,6,1,0,44,47,1,0,3,6,1,0,14,18,1,0,28,33,1,0,19,
		20,1,0,34,35,282,0,42,1,0,0,0,2,45,1,0,0,0,4,49,1,0,0,0,6,53,1,0,0,0,8,
		72,1,0,0,0,10,74,1,0,0,0,12,76,1,0,0,0,14,98,1,0,0,0,16,100,1,0,0,0,18,
		110,1,0,0,0,20,118,1,0,0,0,22,143,1,0,0,0,24,161,1,0,0,0,26,163,1,0,0,
		0,28,166,1,0,0,0,30,173,1,0,0,0,32,182,1,0,0,0,34,203,1,0,0,0,36,224,1,
		0,0,0,38,235,1,0,0,0,40,241,1,0,0,0,42,43,7,0,0,0,43,1,1,0,0,0,44,46,5,
		7,0,0,45,44,1,0,0,0,45,46,1,0,0,0,46,47,1,0,0,0,47,48,7,1,0,0,48,3,1,0,
		0,0,49,50,7,2,0,0,50,5,1,0,0,0,51,54,5,43,0,0,52,54,3,0,0,0,53,51,1,0,
		0,0,53,52,1,0,0,0,54,55,1,0,0,0,55,58,3,4,2,0,56,59,5,43,0,0,57,59,3,0,
		0,0,58,56,1,0,0,0,58,57,1,0,0,0,59,67,1,0,0,0,60,63,3,4,2,0,61,64,5,43,
		0,0,62,64,3,0,0,0,63,61,1,0,0,0,63,62,1,0,0,0,64,66,1,0,0,0,65,60,1,0,
		0,0,66,69,1,0,0,0,67,65,1,0,0,0,67,68,1,0,0,0,68,7,1,0,0,0,69,67,1,0,0,
		0,70,73,5,43,0,0,71,73,3,0,0,0,72,70,1,0,0,0,72,71,1,0,0,0,73,9,1,0,0,
		0,74,75,7,3,0,0,75,11,1,0,0,0,76,77,7,4,0,0,77,13,1,0,0,0,78,79,3,8,4,
		0,79,80,3,10,5,0,80,84,3,8,4,0,81,82,3,12,6,0,82,83,3,14,7,0,83,85,1,0,
		0,0,84,81,1,0,0,0,84,85,1,0,0,0,85,99,1,0,0,0,86,87,5,21,0,0,87,88,5,36,
		0,0,88,89,3,8,4,0,89,90,3,10,5,0,90,94,3,8,4,0,91,92,3,12,6,0,92,93,3,
		14,7,0,93,95,1,0,0,0,94,91,1,0,0,0,94,95,1,0,0,0,95,96,1,0,0,0,96,97,5,
		37,0,0,97,99,1,0,0,0,98,78,1,0,0,0,98,86,1,0,0,0,99,15,1,0,0,0,100,101,
		5,43,0,0,101,102,7,5,0,0,102,17,1,0,0,0,103,111,3,20,10,0,104,105,3,26,
		13,0,105,106,5,40,0,0,106,111,1,0,0,0,107,108,3,30,15,0,108,109,5,40,0,
		0,109,111,1,0,0,0,110,103,1,0,0,0,110,104,1,0,0,0,110,107,1,0,0,0,111,
		112,1,0,0,0,112,110,1,0,0,0,112,113,1,0,0,0,113,114,1,0,0,0,114,115,5,
		0,0,1,115,19,1,0,0,0,116,119,3,2,1,0,117,119,5,8,0,0,118,116,1,0,0,0,118,
		117,1,0,0,0,119,120,1,0,0,0,120,121,5,43,0,0,121,133,5,36,0,0,122,123,
		3,2,1,0,123,130,5,43,0,0,124,125,5,41,0,0,125,126,3,2,1,0,126,127,5,43,
		0,0,127,129,1,0,0,0,128,124,1,0,0,0,129,132,1,0,0,0,130,128,1,0,0,0,130,
		131,1,0,0,0,131,134,1,0,0,0,132,130,1,0,0,0,133,122,1,0,0,0,133,134,1,
		0,0,0,134,135,1,0,0,0,135,136,5,37,0,0,136,137,5,38,0,0,137,138,3,22,11,
		0,138,139,5,39,0,0,139,21,1,0,0,0,140,142,3,24,12,0,141,140,1,0,0,0,142,
		145,1,0,0,0,143,141,1,0,0,0,143,144,1,0,0,0,144,23,1,0,0,0,145,143,1,0,
		0,0,146,153,3,26,13,0,147,153,3,28,14,0,148,153,3,30,15,0,149,153,3,16,
		8,0,150,153,3,38,19,0,151,153,3,40,20,0,152,146,1,0,0,0,152,147,1,0,0,
		0,152,148,1,0,0,0,152,149,1,0,0,0,152,150,1,0,0,0,152,151,1,0,0,0,153,
		154,1,0,0,0,154,155,5,40,0,0,155,162,1,0,0,0,156,160,3,32,16,0,157,160,
		3,34,17,0,158,160,3,36,18,0,159,156,1,0,0,0,159,157,1,0,0,0,159,158,1,
		0,0,0,160,162,1,0,0,0,161,152,1,0,0,0,161,159,1,0,0,0,162,25,1,0,0,0,163,
		164,3,2,1,0,164,165,5,43,0,0,165,27,1,0,0,0,166,167,5,43,0,0,167,171,5,
		22,0,0,168,172,3,0,0,0,169,172,5,43,0,0,170,172,3,6,3,0,171,168,1,0,0,
		0,171,169,1,0,0,0,171,170,1,0,0,0,172,29,1,0,0,0,173,174,3,2,1,0,174,175,
		5,43,0,0,175,180,5,22,0,0,176,181,3,0,0,0,177,181,5,43,0,0,178,181,3,6,
		3,0,179,181,3,40,20,0,180,176,1,0,0,0,180,177,1,0,0,0,180,178,1,0,0,0,
		180,179,1,0,0,0,181,31,1,0,0,0,182,183,5,9,0,0,183,184,5,36,0,0,184,185,
		3,14,7,0,185,191,5,37,0,0,186,192,3,24,12,0,187,188,5,38,0,0,188,189,3,
		22,11,0,189,190,5,39,0,0,190,192,1,0,0,0,191,186,1,0,0,0,191,187,1,0,0,
		0,192,201,1,0,0,0,193,199,5,10,0,0,194,200,3,24,12,0,195,196,5,38,0,0,
		196,197,3,22,11,0,197,198,5,39,0,0,198,200,1,0,0,0,199,194,1,0,0,0,199,
		195,1,0,0,0,200,202,1,0,0,0,201,193,1,0,0,0,201,202,1,0,0,0,202,33,1,0,
		0,0,203,204,5,11,0,0,204,207,5,36,0,0,205,208,3,28,14,0,206,208,3,30,15,
		0,207,205,1,0,0,0,207,206,1,0,0,0,208,209,1,0,0,0,209,210,5,40,0,0,210,
		211,3,14,7,0,211,214,5,40,0,0,212,215,3,16,8,0,213,215,3,28,14,0,214,212,
		1,0,0,0,214,213,1,0,0,0,215,216,1,0,0,0,216,222,5,37,0,0,217,223,3,24,
		12,0,218,219,5,38,0,0,219,220,3,22,11,0,220,221,5,39,0,0,221,223,1,0,0,
		0,222,217,1,0,0,0,222,218,1,0,0,0,223,35,1,0,0,0,224,225,5,12,0,0,225,
		226,5,36,0,0,226,227,3,14,7,0,227,233,5,37,0,0,228,234,3,24,12,0,229,230,
		5,38,0,0,230,231,3,22,11,0,231,232,5,39,0,0,232,234,1,0,0,0,233,228,1,
		0,0,0,233,229,1,0,0,0,234,37,1,0,0,0,235,239,5,13,0,0,236,240,3,0,0,0,
		237,240,5,43,0,0,238,240,3,6,3,0,239,236,1,0,0,0,239,237,1,0,0,0,239,238,
		1,0,0,0,240,39,1,0,0,0,241,242,5,43,0,0,242,257,5,36,0,0,243,246,5,43,
		0,0,244,246,3,0,0,0,245,243,1,0,0,0,245,244,1,0,0,0,246,254,1,0,0,0,247,
		250,5,41,0,0,248,251,5,43,0,0,249,251,3,0,0,0,250,248,1,0,0,0,250,249,
		1,0,0,0,251,253,1,0,0,0,252,247,1,0,0,0,253,256,1,0,0,0,254,252,1,0,0,
		0,254,255,1,0,0,0,255,258,1,0,0,0,256,254,1,0,0,0,257,245,1,0,0,0,257,
		258,1,0,0,0,258,259,1,0,0,0,259,260,5,37,0,0,260,41,1,0,0,0,32,45,53,58,
		63,67,72,84,94,98,110,112,118,130,133,143,152,159,161,171,180,191,199,
		201,207,214,222,233,239,245,250,254,257
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
