//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/lupuf/Git-projects/LFC2/LFC2/OurCompiler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="OurCompilerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IOurCompilerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.pure_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPure_data([NotNull] OurCompilerParser.Pure_dataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type([NotNull] OurCompilerParser.Data_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.any_math_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_math_operator([NotNull] OurCompilerParser.Any_math_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.math_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMath_expr([NotNull] OurCompilerParser.Math_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.comp_val"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp_val([NotNull] OurCompilerParser.Comp_valContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.comparer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparer([NotNull] OurCompilerParser.ComparerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.logic_link"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogic_link([NotNull] OurCompilerParser.Logic_linkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.logic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogic_expr([NotNull] OurCompilerParser.Logic_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.crement_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrement_expr([NotNull] OurCompilerParser.Crement_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] OurCompilerParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] OurCompilerParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.expression_generator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_generator([NotNull] OurCompilerParser.Expression_generatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] OurCompilerParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.var_declar_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_declar_expr([NotNull] OurCompilerParser.Var_declar_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.var_assign_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_assign_expr([NotNull] OurCompilerParser.Var_assign_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.var_decl_assg_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl_assg_expr([NotNull] OurCompilerParser.Var_decl_assg_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.if_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_expr([NotNull] OurCompilerParser.If_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.for_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_expr([NotNull] OurCompilerParser.For_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.while_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_expr([NotNull] OurCompilerParser.While_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OurCompilerParser.return_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_expr([NotNull] OurCompilerParser.Return_exprContext context);
}
